spring:
  profiles:
    active:
    - dev
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#      settings:
#        web-allow-others: true
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/capture
#    username: postgres
#    password: admin
  jpa:
    properties:
      javax:
        persistence:
          validation:
            mode: none

#    hibernate:
#      ddl-auto: create # When you launch the application for the first time - switch "none" at "create"
#    show-sql: true
#    database: postgresql
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    open-in-view: false
#    generate-ddl: true
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 100
---
spring:
  profiles: prod
  datasource:
    url: jdbc:h2:./hoaxify-prod
    username: sa
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: false
---
spring:
  profiles: dev
#  datasource:
#    url: jdbc:h2:mem:hoaxify-dev
---
spring:
  profiles: test
  